backend:
  name: github
  repo: VihaanVinoth/vihaanvinoth.github.io
  branch: main
  auth_type: implicit
  app_id: "Ov23li3UPpcWezvmlLA9"

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

site_url: /
display_url: /
preview_path: /

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Cover", name: "cover", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }