backend:
  name: github
  repo: VihaanVinoth/vihaanvinoth.github.io
  branch: main
  auth_type: implicit
  app_id: "Ov23li3UPpcWezvmlLA9"

publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
    preview_styles: ["/style.css"]

preview: |
  <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>${slug}</title>
        <link rel="stylesheet" href="../stylesheets/style.css">
        <link rel="stylesheet" href="../stylesheets/reset.css">
        <meta name="description" content="${summary}">
    </head>
    <body>
        <main>
            <section class="article">
                <header>
                    <h1>${title}</h1>
                    ${date ? `<time datetime=${date}">${date}</time>` : ""}
                    ${summary ? `<p class="summary">${summary}</p>` : ""}
                </header>
                ${htmlBody}
            </section>
        </main>
    </body>
    </html>
